#!/usr/bin/env bash

if jack_lsp -c | grep my-combined-sink; then
    echo custom sink already created
else
    pactl load-module module-null-sink media.class=Audio/Sink sink_name=my-combined-sink channel_map=stereo
fi


my_sink_L="my-combined-sink Audio/Sink sink Monitor:monitor_FL"
my_sink_R="my-combined-sink Audio/Sink sink Monitor:monitor_FR"

g733_R="G733 Gaming Headset Analog Stereo:playback_FR"
g733_L="G733 Gaming Headset Analog Stereo:playback_FL"

build_in_L="Built-in Audio Analog Stereo:playback_FL"
build_in_R="Built-in Audio Analog Stereo:playback_FR"

buds_R="Galaxy Buds Pro (5BEF):playback_FR"
buds_L="Galaxy Buds Pro (5BEF):playback_FL"

monitor_L="GP106 High Definition Audio Controller Digital Stereo (HDMI):playback_FL"
monitor_R="GP106 High Definition Audio Controller Digital Stereo (HDMI):playback_FR"

if jack_lsp -c | grep "GP106 High Definition Audio"; then
    echo Monitor
    jack_connect "$my_sink_R" "$monitor_R"
    jack_connect "$my_sink_L" "$monitor_L"
fi

if jack_lsp -c | grep "Galaxy Buds Pro"; then
    echo Galaxy buds
    jack_connect "$my_sink_R" "$buds_R"
    jack_connect "$my_sink_L" "$buds_L"

    jack_disconnect "$my_sink_R" "$g733_R"
    jack_disconnect "$my_sink_L" "$g733_L"
 
    jack_disconnect "$my_sink_L" "$build_in_L"
    jack_disconnect "$my_sink_R" "$build_in_R"
elif jack_lsp -c | grep G733; then
    echo G733
    jack_connect "$my_sink_R" "$g733_R"
    jack_connect "$my_sink_L" "$g733_L"

    jack_disconnect "$my_sink_L" "$build_in_L"
    jack_disconnect "$my_sink_R" "$build_in_R"

    jack_disconnect "$my_sink_R" "$buds_R"
    jack_disconnect "$my_sink_L" "$buds_L"
else
    echo Build in
    jack_connect "$my_sink_L" "$build_in_L"
    jack_connect "$my_sink_R" "$build_in_R"
    
    jack_disconnect "$my_sink_R" "$buds_R"
    jack_disconnect "$my_sink_L" "$buds_L"
    
    jack_disconnect "$my_sink_R" "$g733_R"
    jack_disconnect "$my_sink_L" "$g733_L"
fi
