#!/usr/bin/env bash
dotFiles=$(builtin cd $(dirname -- "$0")/..; pwd)
find $dotFiles -type d -not -path '*/\.git/*' -exec bash -c 'mkdir ~/$(realpath --relative-to="'$dotFiles'" "{}")' \;
find $dotFiles -type f -not -path '*/\.git/*' -exec bash -c 'cp "{}" ~/$(realpath --relative-to="'$dotFiles'" "{}")' \;
