#!/usr/bin/env bash

BLANK='#00000000'
CLEAR='#ffffff22'
TEXT='#114bbfee'
WRONG='#880000bb'
VERIFYING="$TEXT"
DEFAULT="$TEXT"

i3lock \
	   --insidever-color=$CLEAR     \
	   --ringver-color=$VERIFYING   \
	   \
	   --insidewrong-color=$CLEAR   \
	   --ringwrong-color=$WRONG     \
	   \
	   --inside-color=$BLANK        \
	   --ring-color=$DEFAULT        \
	   --line-color=$BLANK          \
	   --separator-color=$DEFAULT   \
	   \
	   --verif-color=$TEXT          \
	   --wrong-color=$TEXT          \
	   --time-color=$TEXT           \
	   --date-color=$TEXT           \
	   --layout-color=$TEXT         \
	   --keyhl-color=$WRONG         \
	   --bshl-color=$WRONG          \
	   \
	   --screen 1                   \
	   --blur  7                    \
	   --clock                      \
	   --indicator                  \
	   --time-str="%H:%M:%S"        \
	   --date-str="%A, %Y-%m-%d"       \
	   --keylayout 1                \
