#!/usr/bin/env bash
# SHIT NEED TO BE HERE
copyq &
pasystray &
blueman-applet  &
flameshot &
feh --bg-fill ~/Pictures/background.* &
setxkbmap -layout us,cz -option grp:alt_shift_toggle

eval `ssh-agent`

emacs --daemon &

(sleep 2 && systemctl --user restart dwm-status.service) &

(sleep 1 && /home/martin/GitHub/Martin/DotFiles/scripts/audio-devices) &

DWM_LOG="/tmp/dwm.log"
DWM_LOG_OLD="$DWM_LOG.old"
if [[ -f "$DWM_LOG" ]]; then
    mv "$DWM_LOG" "$DWM_LOG_OLD"
fi

DWM_LOG_ERROR="/tmp/dwm_err.log"
DWM_LOG_ERROR_OLD="$DWM_LOG_ERROR.old"
if [[ -f "$DWM_LOG_ERROR" ]]; then
    mv "$DWM_LOG_ERROR" "$DWM_LOG_ERROR_OLD"
fi

autorandr --change

dwm > "$DWM_LOG" 2> "$DWM_LOG_ERROR"
